version: '3.3'
services:
    trainer:
        restart: always
        build: Trainer_Service/.
        ports:
        - 5000:5000
        depends_on:
            - mongo
    course:
        restart: always
        build: Course_Service/.
        ports:
        - 6000:6000
        depends_on:
            - mongo
    auth:
        restart: always
        build: Auth_Service/.
        ports:
        - 7000:7000
        depends_on:
            - mongo
    mongo:
        ports:
            - 27017:27017
        container_name: dkrcomp-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo