version: '3.3'
services:
    course:
        restart: always
        build: Course_Service/.
        ports:
        - 6000:6000
        depends_on:
            - mongo
        environment:
            - NODE_ENV=production
    mongo:
        ports:
            - 27017:27017
        restart: always
        logging:
            options:
                max-size: 1g
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo