version: '3.3'
services:
    node:
        restart: always
        build: .
        ports:
        - 6000:6000
        depends_on:
            - mongo
    mongocourse:
        ports:
            - 27017:27017
        container_name: mongocourse-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        #     - MONGO_INITDB_ROOT_PASSWORD=bdung
        image: mongo